teamproject/soundbored/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import ResetPasswordView

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('upload/', views.audio_upload_view, name='audio_upload'),
    path('', views.audio_list_view, name='audio_list'),
    path('delete/<int:audio_id>/', views.delete_audio, name='delete_audio'),
    path('favorite/<int:audio_id>/', views.toggle_favorite, name='toggle_favorite'),
    path('favorites/', views.list_favorites, name='list_favorites'),
    path('soundboard/', views.soundboard_view, name='soundboard_view'),
    path('soundboard/upload', views.soundboard_upload_view, name='soundboard_upload_view'),
    path('soundboard/<int:pk>/', views.soundboard_view, name='soundboard_view'),
    path('my-soundboards/', views.my_soundboards_view, name='my_soundboards'),
    path('soundboard/delete/<int:pk>/', views.delete_soundboard, name='delete_soundboard'),
    path('register/', views.register_view, name='register'),
    path('my-sounds/', views.my_sounds_view, name='my_sounds'),
    path('password_reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='soundbored/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='soundbored/password_reset_complete.html'),
         name='password_reset_complete'),
]

teamproject/teamproject/urls.py
from django.contrib import admin
from django.urls import path, include  # Include the include() function
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Include your app's URLs. Adjust the path as needed.
    path('audio/', include('soundbored.urls')),  # This line includes `soundbored`'s URLs under `/audio/`
    # If you want `soundbored`'s URLs to be at the root, use path('', include('soundbored.urls')),
    path('', include('soundbored.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teamproject/soundbored/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User


class Audio(models.Model):
    title = models.CharField(max_length=255)
    audio_file = models.FileField(
        upload_to='audios/', validators=[FileExtensionValidator(allowed_extensions=['mp3'])])
    image = models.ImageField(
        upload_to='images/', default='images/defaultpic.png')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    favorites = models.ManyToManyField(User, related_name='favorite_audios')
    uploader = models.ForeignKey(
        User, null=True, on_delete=models.CASCADE, related_name='uploaded_audios')

class SoundBoard(models.Model):
    title = models.CharField(max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='soundboards', null=True)
    audios = models.ManyToManyField(Audio, related_name='included_in_soundboards')

teamproject/soundbored/forms.py
from django import forms
from .models import Audio, SoundBoard
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ['title', 'audio_file', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Title'}),
            'audio_file': forms.FileInput(attrs={'class': 'audio-button'}),
            'image': forms.FileInput(attrs={'class': 'audio-button'}),
        }


class SoundBoardForm(forms.ModelForm):
    audios = forms.ModelMultipleChoiceField(
        queryset=Audio.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = SoundBoard
        fields = ['title', 'audios']


class NewUserForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form__input', 'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form__input', 'placeholder': 'Email'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form__input', 'placeholder': 'Password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form__input', 'placeholder': 'Retype Password'}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class EmailForm(forms.Form):
    email = forms.EmailField(label='Enter your email')

teamproject/soundbored/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AudioForm, SoundBoardForm, NewUserForm
from .models import Audio, SoundBoard
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import NewUserForm
from .forms import EmailForm
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django import template


# Login Veiw for user authentication
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        # User exists
        if user is not None:
            login(request, user)
            # Redirect to home
            return redirect('audio_list')
        # User doesn't exist
        else:
            error_message = 'Invalid username or password'
            return render(request, 'soundbored/login.html', {'error_message': error_message})
    return render(request, 'soundbored/login.html')


# Logout Veiw
def logout_view(request):
    logout(request)
    return redirect('audio_list')


# Existing audio list view
def audio_list_view(request):
    audios = Audio.objects.all()
    return render(request, 'soundbored/audio_list.html', {'audios': audios, 'logged_in': request.user.is_authenticated})










# My Soundboards
@login_required
def soundboard_upload_view(request):
    if request.method == 'POST':
        form = SoundBoardForm(request.POST)
        if form.is_valid():
            new_soundboard = SoundBoard(
                title=form.cleaned_data['title'],
                owner=request.user
            )
            new_soundboard.save()
            new_soundboard.audios.set(form.cleaned_data['audios'])
            new_soundboard.save()
            # Redirect to the 'My Soundboards' view after successful upload
            return redirect('my_soundboards')
    else:
        form = SoundBoardForm()
    audios = Audio.objects.all()
    return render(request, 'soundbored/soundboard_upload.html', {'form': form, 'audios': audios})


@login_required
def my_soundboards_view(request):
    soundboards = SoundBoard.objects.filter(owner=request.user)
    return render(request, 'soundbored/my_soundboards.html', {'soundboards': soundboards})


def soundboard_view(request, pk=None):
    if pk:
        soundboard = get_object_or_404(SoundBoard, pk=pk)
    else:
        return redirect('my_soundboards')

    return render(request, 'soundbored/soundboard.html', {'soundboard': soundboard})

# used for refffffffrence 
# @login_required
# def soundboard_detail_view(request, pk):
#     soundboard = get_object_or_404(SoundBoard, pk=pk, owner=request.user)  # Ensure ownership
#     if request.method == 'POST':
#         form = SoundBoardForm(request.POST, instance=soundboard)
#         if form.is_valid():
#             form.save()
#             return redirect('soundboard_detail', pk=soundboard.pk)
#     else:
#         form = SoundBoardForm(instance=soundboard)
#     return render(request, 'soundbored/soundboard_detail.html', {'form': form, 'soundboard': soundboard})


@login_required
def delete_soundboard(request, pk):
    soundboard = get_object_or_404(SoundBoard, pk=pk, owner=request.user)  # Ensures that only the owner can delete
    soundboard.delete()
    return redirect('my_soundboards')  # Redirects back to the list of soundboards











# Upload view
@ login_required
def audio_upload_view(request):
    if request.method == 'POST':
        form = AudioForm(request.POST, request.FILES)
        if form.is_valid():
            audio = form.save(commit=False)
            audio.uploader = request.user  # Set the uploader to the current user
            audio.save()
            # Redirect to 'My Sounds' view after upload
            return redirect('my_sounds')
    else:
        form = AudioForm()
    return render(request, 'soundbored/audio_upload.html', {'form': form})


# Favorites
@ login_required
def toggle_favorite(request, audio_id):
    audio = get_object_or_404(Audio, pk=audio_id)
    if request.user in audio.favorites.all():
        audio.favorites.remove(request.user)
    else:
        audio.favorites.add(request.user)
    # Return to current url after toggled
    return redirect(request.META.get('HTTP_REFERER'))


# My Sounds View
@ login_required
def my_sounds_view(request):
    # Fetch audios uploaded by the user
    user_audios = request.user.uploaded_audios.all()
    return render(request, 'soundbored/my_sounds.html', {'audios': user_audios, 'delete_button': True})


# Favorites View
@ login_required
def list_favorites(request):
    user_favorites = request.user.favorite_audios.all()
    return render(request, 'soundbored/favorites_list.html', {'favorites': user_favorites})


def delete_audio(request, audio_id):
    # Get the audio object, and if it doesn't exist, return a 404 error
    audio = get_object_or_404(Audio, pk=audio_id)
    audio.delete()  # Delete the audio object
    return redirect('my_sounds')  # Redirect to the audio list page


def add_favorite(request, audio_id):
    # Get the audio object, and if it doesn't exist, return a 404 error
    audio = get_object_or_404(Audio, pk=audio_id)
    audio.is_favorite = not audio.is_favorite  # Toggle the favorite status
    audio.save()
    return redirect('audio_list')  # Redirect to the audio list page


def register_view(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            # If you want to log the user in and redirect to a new page:
            # login(request, user)
            # redirect to the desired page
            return redirect(reverse('login'))  # Redirect them to login page
    else:
        form = NewUserForm()
    return render(request, 'soundbored/register.html', {"form": form})


def password_reset(request):
    form = EmailForm()
    return render(request, 'soundbored/password_reset_form.html', {'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'soundbored/password_reset.html'
    email_template_name = 'soundbored/password_reset_email.html'
    subject_template_name = 'soundbored/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
        "if an account exists with the email you entered. You should receive them shortly." \
        " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('password_reset')

teamproject/soundbored/templates/soundbored/audio_list.html
{% extends "soundbored/base_template.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
</head>

{% block content %}
<body>
<div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
  <div class="text-center" style="display: flex; align-items: center;">
    <img src="{% static 'src/icons/sound_wave.svg' %}" class="title-icon">
    <h1 class="text-center font-title title">Explore Our Sound Library</h1>
  </div>
  <div class="row">
    {% for audio in audios %}
      {% include 'includes/audio_button.html' %}
    {% endfor %}
  </div>
</div>
</body>
{% endblock content %}
</html>

teamproject/soundbored/templates/soundbored/audio_upload.html
{% extends "soundbored/base_template.html" %}
{% load static %}

<!DOCTYPE html>
<head>
    <title>Upload MP3</title>
</head>

{% block content %}
  <div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
    <h1 class="font-title title">Upload Your Sound</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        {{ form.title }}
      </div>
      <div class="form-group m-2">
        {{ form.audio_file.label_tag }}
        {{ form.audio_file }}
      </div>
      <div class="form-group m-2">
        {{ form.image.label_tag }}
        {{ form.image }}
      </div>
      <div class="flex-row">
        <button class="sub-button" type="submit">Upload</button>
        <img style="border-radius: 20px; margin-left: 3%; width: 10em;" src="{% static 'src/unicorn_dj.png' %}">
      </div>
  </div>
{% endblock content %}

teamproject/soundbored/templates/soundbored/base_template.html
<!DOCTYPE html>
<html>
<head>
    <title>Sound-Bored</title>
    {% block head %}
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'src/icons/floppy.ico' %}">
    <script src="{% static 'scripts/audio.js' %}"></script>
    <link rel="stylesheet" href="{% static 'styles/base_template.css' %}">
    <link rel="stylesheet" href="{% static 'styles/audio_list.css' %}">
    <link rel="stylesheet" href="{% static 'styles/audio_upload.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jersey+10&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jersey+10&family=Signika+Negative:wght@300..700&display=swap" rel="stylesheet">
    {% endblock %}
</head>
<body>
      <!--Side Navbar -->
    <div class="d-flex" style="min-height: 100vh; background-color: #d5cfbe;">
        <!-- Side navbar -->
        <nav class="navbar-light nav-container p-2">
        <button class="nav-button" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-container custom-nav flex-column" style="width: 16vw;" id="navbarNav">
            <div style="flex-direction: column; justify-content: space-between;">
            <ul class="navbar-nav flex-column">
                <li class="nav-item nav-item-custom">
                    <a class="nav-link nav-link-custom" href="{% url 'audio_list' %}">Home</a>
                </li>
                <li class="nav-item nav-item-custom">
                  {% if user.is_authenticated %}
                  <a class="nav-link nav-link-custom" href="{% url 'my_sounds' %}">My Sounds</a>
                  {% else %}
                  <a class="nav-link nav-link-custom" href="{% url 'login' %}">My Sounds</a>
                  {% endif %}
                </li>
                <li class="nav-item nav-item-custom">
                  {% if user.is_authenticated %}
                <a class="nav-link nav-link-custom" href="{% url 'soundboard_view' %}">My Sound Bored's</a>
                  {% else %}
                <a class="nav-link nav-link-custom" href="{% url 'login' %}">My Sound Bored's</a>
                  {% endif %}
                </li>
                <li class="nav-item nav-item-custom">
                  {% if user.is_authenticated %}
                    <a class="nav-link nav-link-custom" href="{% url 'list_favorites' %}">My Favorites</a>
                  {% else %}
                    <a class="nav-link nav-link-custom" href="{% url 'login' %}">My Favorites</a>
                  {% endif %}
                </li>
                <li class="nav-item nav-item-custom">
                  {% if user.is_authenticated %}
                    <a class="nav-link nav-link-custom" href="{% url 'audio_upload' %}">Upload Sounds</a>
                  {% else %}
                    <a class="nav-link nav-link-custom" href="{% url 'login' %}">Upload Sounds</a>
                  {% endif %}
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item nav-item-custom">
                    <a href="{% url 'logout' %}" class="nav-link nav-link-custom" style="color: red;">Logout</a>
                </li>
                {% else %}
                <li class="nav-item nav-item-custom">
                    <a href="{% url 'login' %}" class="nav-link nav-link-custom" style="color: green;">Login</a>
                </li>
                {% endif %}
                </ul>
            </div>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
      <div class="right-columns" style="min-height: 100%;">
        <div class="column1"></div>
        <div class="column2"></div>
        <div class="column3"></div>
        <div class="column4"></div>
      </div>
  </div>
</body>
</html>

teamproject/soundbored/templates/soundbored/favorites_list.html
{% extends "soundbored/base_template.html" %}

<!DOCTYPE html>
<head>
    <title>My Favorites</title>
    {% load static %}
</head>

{% block content %}
    <div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
    <h1 class="font-title title">{{user}}'s Favorites</h1>
        <div class ="row">
          {% for audio in favorites %}
            {% include 'includes/audio_button.html' %}
          {% endfor %}
        </div>
      </div>
{% endblock content %}

teamproject/soundbored/templates/soundbored/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login to Soundbored!</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jersey+10&display=swap" rel="stylesheet">
</head>
<body>
  {% block content %}
  {% if error_message %}
    <div class="alert alert-danger">{{ error_message }}</div>
  {% endif %}
  <div class="container-fluid" style="display: flex; justify-content: center; margin-top: 25vh;">
    <div class="row main-content bg-success text-center">
      <div class="col-md-4 text-center company__info">
      </div>
      <div class="col-md-8 col-xs-12 col-sm-12 login_form">
        <div class="container-fluid">
          <div class="row">
            <h2 class="font-title">Log In</h2>
          </div>
          <form method="post">
          {% csrf_token %}
          <div class="row">
            <form control="" class="form-group">
              <div class="row">
                  <input class="form__input" id="username" name="username" placeholder="Username" required>
              </div>
              <div class="row">
                <input class="form__input" type="password" id="password" name="password" placeholder="Password" required>
              </div>
              <div class="row">
                <input type="submit" value="Login" class="btn">
              </div>
            </form>
          </div>
          <div class="row">
            <p>Don't have an account? <a href="{% url 'register' %}">Register Here</a> | <a href="{% url 'password_reset' %}">Forgot Password?</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}
</body>
</html>

teamproject/soundbored/templates/soundbored/my_soundboards.html
{% extends "soundbored/base_template.html" %}
{% load static %}
{% block content %}
<body>
  <div class="flex-container p-4" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
    <div class="text-center" style="display: flex; align-items: center;">
      <h1 class="font-title title">My Sound Boreds</h1>
    </div>
    <div class="row">
      {% for soundboard in soundboards %}
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 text-center py-4">
          <div class="d-button-container">
            <a href="{% url 'delete_soundboard' soundboard.pk %}" class="delete-button" onclick="return confirm('Are you sure you want to delete {{ soundboard.title }}?');">✖</a>
            <img src="{% static 'src/soundboard.png' %}" style="height: 90%; width: 90%; border-radius: 30%;" onclick="location.href='{% url 'soundboard_view' soundboard.pk %}'"></img>
          </div>
          <h2 class="text-center font-sound-title" style="margin-top: 4px; font-size: 20px;">{{ soundboard.title }}</h2>
        </div>
      {% endfor %}
    </div>
    <a class="btn" style="margin-top: 10vh; margin-left: 4vw; background-color: white; color: #3B3B3B; border: 2px solid #1A1A1A; font-weight: 600;" href="{% url 'soundboard_upload_view' %}">Create A New Sound-Bored</a>
  </div>
</body>
{% endblock %}

teamproject/soundbored/templates/soundbored/my_sounds.html
{% extends "soundbored/base_template.html" %}
{% load static %}

{% block content %}
  <div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
    <h1 class="font-title title">{{user}}'s Sounds</h1>
      <div class="row">
      {% for audio in audios %}
        {% include 'includes/audio_button.html' %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

teamproject/soundbored/templates/soundbored/password_reset.html
{% extends "soundbored/base_template.html" %}
<!DOCTYPE html>

<head>
    <title>Password Reset</title>
</head>

{% block content %}
  <div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
    <h1 class="font-title">Password Reset</h1>
    <div class="form-content my-3 p-3">
        <div class="container">
            
                <div class="">
                    <div class="">
                        
                            <div id="error_div"></div>
                          <h2 class="font-weight-light my-4 text-center">Forgot Password?</h2>
                        
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email" style="text-align:center"><h4>Send Password Recovery Email</h4></label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <br>
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class=" text-center">
                            <div class="small">
                                <a href="{% url 'register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            
        </div>

  </div>
  </div>
{% endblock content %}

teamproject/soundbored/templates/soundbored/password_reset_complete.html
{% extends "soundbored/base_template.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="alert alert-warning">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
            </div>
        </div>
    </div>
{% endblock content %}

teamproject/soundbored/templates/soundbored/password_reset_confirm.html
{% extends "soundbored/base_template.html" %}

{% block content %}
    <div class="flex-container p-3" style="width: 100vw; background-color: #ddddc6; color: #1d1e2c;">
        <h1 class="font-title">Password Reset Form</h1>
        <div class="form-content my-3 p-3">
        <div class="container">

            <div class="">
                <div class="
                ">
                    {% if validlink %}
                            <div class="justify-content-center">
                              <h2 class="font-weight-light my-4 text-center">Reset Your Password</h2>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1"><h4>New Password</h4></label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2"><h4>New Password Confirmation</h4></label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
        </div>
    </div>
{% endblock %}

teamproject/soundbored/templates/soundbored/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} SoundBored account,
  click the link below:


  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The SoundBored Team
{% endautoescape %}